[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MicroMAP"
authors = [{name = "João Pedro C. Moreira", email = "mcjpedro@gmail.com"}]
dynamic = ["version", "description"]
